export default data = [
  {
    id: 1,
    name: 'Steel Cup',
    picture: require('../../config/images/products/steelcup.jpeg'),
    price: 100,
    category: ['cup', 'steel'],
    description: 'This is a steel cup you can drink tea or coffee',
    images: [
      require('../../config/images/products/steelcup.jpeg'),
      require('../../config/images/products/jug.jpeg'),
    ],
    brand: 'Tata',
    countInStock: 2,
  },
  {
    id: 2,
    name: 'Copper Steel Jug',
    picture: require('../../config/images/products/jug.jpeg'),
    price: 900,
    category: ['copper', 'steel'],
    description: 'This is a copper jug you can drink water',
    brand: 'Saga',
    countInStock: 6,
  },
  {
    id: 3,
    name: 'Porcelian Cup',
    picture: require('../../config/images/products/matacup.jpeg'),
    price: 100,
    category: 'cup',
    description: 'This is a Porcelian cup you can drink tea or coffee',
    images: [
      require('../../config/images/products/steelcup.jpeg'),
      require('../../config/images/products/jug.jpeg'),
    ],
    brand: 'Por',
    countInStock: 5,
  },
  {
    id: 4,
    name: 'Brass Masala Grinding',
    picture: require('../../config/images/products/5.jpeg'),
    price: 500,
    category: 'brass',
    description: 'This is a Porcelian cup you can drink tea or coffee',
    images: [
      require('../../config/images/products/steelcup.jpeg'),
      require('../../config/images/products/jug.jpeg'),
    ],
    brand: 'Hulas',
    countInStock: 3,
  },
  {
    id: 5,
    name: 'Bhada Stand',
    picture: require('../../config/images/products/stand.jpeg'),
    price: 120,
    category: 'steel',
    description: 'This is a Porcelian cup you can drink tea or coffee',
    images: [
      require('../../config/images/products/steelcup.jpeg'),
      require('../../config/images/products/jug.jpeg'),
    ],
    brand: 'Steel',
    countInStock: 7,
  },
];
